runtime! macros/matchit.vim                           " Find matching ( ), [ ], { } and def/end

" indent guide config - assumes colorscheme passed from terminal
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=black ctermbg=0
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=black ctermbg=6
filetype plugin on                                    " enable ctag plugin
set tags+=gems.tags                                   " add gems.tags (generated by guard-ctags-bundler) to list of inspected ctags

